---
- hosts: all
  become: true
  tasks:
   - name: Create directory
     file:
       path: /home/diegosoda/tomcat
       state: directory
       owner: diegosoda
       group: diegosoda
       mode: 775     
